DROP TABLE IF EXISTS 'REL_COCKTAIL_INGREDIENT';
DROP TABLE IF EXISTS 'INGREDIENT';
DROP TABLE IF EXISTS 'COCKTAIL';
CREATE TABLE 'COCKTAIL' (
	'ID_COCKTAIL'	INT,
	'NAME'	VARCHAR(200) NOT NULL,
	'AUTHOR'	VARCHAR(200),
	'IMAGE_URL'	VARCHAR(200) NOT NULL,
	'INFO'	VARCHAR(2000),
	'PREPARATION'	VARCHAR(5000) NOT NULL,
	PRIMARY KEY('ID_COCKTAIL')
);
CREATE TABLE 'INGREDIENT' (
	'ID_INGREDIENT'	INT,
	'NAME'	VARCHAR(200) NOT NULL,
	PRIMARY KEY('ID_INGREDIENT')
);
CREATE TABLE 'REL_COCKTAIL_INGREDIENT' (
	'ID_COCKTAIL_INGREDIENT'	INT,
	'ID_COCKTAIL'	INT NOT NULL,
	'ID_INGREDIENT'	INT NOT NULL,
	'AMOUNT'	VARCHAR(200) NOT NULL,
	FOREIGN KEY('ID_INGREDIENT') REFERENCES 'INGREDIENT'('ID_INGREDIENT'),
	FOREIGN KEY('ID_COCKTAIL') REFERENCES 'COCKTAIL'('ID_COCKTAIL'),
	PRIMARY KEY('ID_COCKTAIL_INGREDIENT')
);
INSERT INTO 'COCKTAIL' ('ID_COCKTAIL','NAME','AUTHOR','IMAGE_URL','INFO','PREPARATION') VALUES 
 (1,'Bellini','antoniosa','c01','Uno de los principales cócteles fáciles de preparar es el bellini, un trago típico de Venecia creado en 1948. Se dice que su nombre viene del pintor renacentista Giovanni Bellini, famoso por emplear el color rosa en sus pinturas. Además, se convirtió en la bebida favorita de grandes personajes como Ernest Hemingway y Orson Welles.','Prepara el zumo licuando los duraznos. Puedes agregar hielo mientras licuas. Este cocktail se sirve en una copa de champán. Agrega el zumo y luego el champán. Cuidadosamente, mezcla con una cucharilla larga hasta que todo se una. Para darle el tono rosa que tradicionalmente lleva, agrega zumo de cereza. También puedes utilizar un champán rosado.'),
 (2,'Tequila sunrise','cechope','c02','Como su nombre indica, el tequila sunrise se prepara con tequila. Se creó en un hotel de Phoenix en Estados Unidos y su nombre ''sunrise'' se debe a los colores que se ven en el vaso, que son semejantes a los del amanecer.','Coloca el hielo en un vaso largo y agrega el tequila y el zumo de naranja. Incorpora la granadina y remueve. Así crearás el efecto cromático. Decora con una cereza o un trozo de naranja.'),
 (3,'Daiquiri','armandoroa','c03','Entre los cócteles fáciles de preparar con ron destaca el daiquiri, una bebida originaria de Cuba. La creó un ingeniero estadounidense que trabajaba en unas minas con el nombre de este trago.','Licua todos los ingredientes con el hielo y coloca la mezcla en una coctelera. Agita, cuela y sirve en una copa para margaritas.'),
 (4,'Mojito','sofiass','c04','Entre los cócteles fáciles de preparar no puede faltar el mojito. Se dice que a, finales del siglo XVI, se realizó la primera versión de este cocktail, que, en ese momento, llevaba aguardiente en lugar de ron. Se utilizaba como remedio para combatir el escorbuto o falta de vitamina C, muy típica entre los marineros de la época.','En un vaso largo, machaca las hojas de hierbabuena con el azúcar y el zumo de limón. Añade un chorrito de soda. Agrega el hielo, el ron y llena lo que queda con un poco más de soda. Decora con unas hojas de hierbabuena o una rodaja de limón.'),
 (5,'Gin tonic','sebasoroz','c05','El gin tonic comenzó siendo una medicina preventiva en casos de malaria, ya que la preparaban con quinina, una sustancia que se extraía de los arboles. A ella se agregaban agua y aromatizantes. Más adelante, se sustituyó el agua por la soda, ya que era mejor de digerir. Dado que su sabor era bastante malo, decidieron agregarle alcohol y, para esto, utilizaron la ginebra.','Para este cocktail, utiliza un vaso ancho o una copa de balón. Agrega el hielo y deja que el vaso se enfríe. Escurre el agua y echa directamente la ginebra y la soda en el vaso. Decora con la cáscara del limón. La idea de este cocktail es que las burbujas se mantengan. Por ello no es recomendable poner el zumo o la pulpa de las frutas'),
 (6,'Black russian','juancaso','c06','Este cóctel fácil de preparar,¡Un combinado con glamour el cóctel Black russian!, creado en honor de una diplomática estadounidense en 1940. Si te gusta el licor de café y el vodka no dejes de probar este cóctel.','Utiliza un vaso ancho para la preparación de este trago. Pon el hielo y agrega los ingredientes. Luego, remueve suavemente. Este cóctel tiene una variante llamada white russian al que se le agrega un poco de nata por encima y se mueve ligeramente.'),
 (7,'Cuba libre','johnrod','c07','un cóctel muy famoso y que se elabora con muy pocos ingredientes y hielo, de ahí que resulte refrescante y todo un éxito. Su origen tuvo lugar en la Habana, en Cuba, al inicio del siglo XX, cuando soldados estadounidenses empezaron a beber esta mezcla de Coca cola y Ron Bacardí y brindaron ¡Por Cuba Libre! celebrando la reciente liberación de Cuba.','Sirve este trago en un vaso largo. Agrega el hielo, el ron, el refresco, el limón y, por último, unas gotas de amargo de angostura, una mezcla de raíces, semillas aromáticas, frutas y cortezas. ¡Listo! Ya puedes disfrutar de uno de los mejores cócteles fáciles de prepara'),
 (8,'Margarita','alejandroroa','c08','Sin duda, uno de los cócteles fáciles para fiestas más destacados es el margarita. Hay muchas historias alrededor de esta bebida. Una de ellas es que la margarita fue creada en 1938 por el dueño de un restaurante mexicano para un cliente que era alérgico a todos los licores excepto al tequila.','Mezcla todos los ingredientes junto con el hielo en un coctelera. Agita bien, cuela, sirve en una copa y decora el borde con sal.'),
 (9,'Dry Martini','andresguss','c09','El dry martini fue creado en 1910 por un jefe de barra en un club de Nueva York. Sin embargo existen muchas historias acerca de su historia y la exactitud de sus ingredientes, pero sí hay algo claro: es uno de los mejores cócteles fáciles con ginebra','Coloca todos los ingredientes en una coctelera con hielo, remueve bien y sírvelo en una copa fría.'),
 (10,'Piña colada','tomasfind','c10','La receta de piña colada es uno de los cócteles con frutas más populares en todo el mundo. Aunque hay muchas historias sobre su origen, la piña colada proviene de Puerto Rico y es una de las bebidas más disfrutadas en las playas del Caribe.','Coloca todos los ingredientes en una licuadora, incluyendo el hielo. Sírvelo en una copa grande con una rodaja de piña y una pajita. Ya está todo listo para disfrutar de uno de los mejores cócteles con alcohol.');
INSERT INTO 'INGREDIENT' ('ID_INGREDIENT','NAME') VALUES 
 (1,'champan'),
 (2,'zumo de durazno'),
 (3,'zumo de cerezas'),
 (4,'tequila'),
 (5,'zumo de naranja'),
 (6,'granada'),
 (7,'hielo'),
 (8,'pulpa de fruta'),
 (9,'ron blanco'),
 (10,'zumo de limon'),
 (11,'azucar'),
 (12,'licor de frutas'),
 (13,'rama de menta'),
 (14,'azucar morena'),
 (15,'soda'),
 (16,'ginebra'),
 (17,'limon'),
 (18,'vodka'),
 (19,'licor de cafe'),
 (20,'ron'),
 (21,'refresco de cola'),
 (22,'triple seco'),
 (23,'vermu seco'),
 (24,'zumo de piña'),
 (25,'leche de coco');
INSERT INTO 'REL_COCKTAIL_INGREDIENT' ('ID_COCKTAIL_INGREDIENT','ID_COCKTAIL','ID_INGREDIENT','AMOUNT') 
 VALUES (1,1,1,'2 OZ'),
 (2,1,2,'2 oz'),
 (3,1,3,'1 oz'),
 (4,2,4,'2 oz'),
 (5,2,5,'4 oz'),
 (6,2,6,'1/4'),
 (7,2,7,' '),
 (8,3,8,'1/2 taza'),
 (9,3,9,'2 oz'),
 (10,3,10,'1 oz'),
 (11,3,11,'2 chucharadas'),
 (12,3,12,'1 oz'),
 (13,3,7,' '),
 (14,4,9,'2 oz'),
 (15,4,10,'1/2'),
 (16,4,13,'1 rama'),
 (17,4,14,'2 cucharaditas'),
 (18,4,7,' '),
 (19,4,15,' '),
 (20,5,16,'2 oz'),
 (21,5,15,'4 oz'),
 (22,5,17,'1 cascara'),
 (23,5,7,' '),
 (24,6,18,'3 oz'),
 (25,6,19,'1 oz'),
 (26,6,7,' '),
 (27,7,20,'4 oz'),
 (28,7,21,'8 oz'),
 (29,7,10,'1 oz'),
 (30,7,7,' '),
 (31,8,4,'2 oz'),
 (32,8,22,'1/2 oz'),
 (33,8,10,'1 oz'),
 (34,8,7,' '),
 (35,9,16,'60 ml'),
 (36,9,23,'10 ml'),
 (37,10,9,'3 oz'),
 (38,10,24,'6 oz'),
 (39,10,25,'3 oz'),
 (40,10,7,' ');